tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'readline'
brew 'bash'
brew 'pcre2'
brew 'gdbm'
brew 'openssl'
brew 'mongodb'
brew 'node'
brew 'pcre'
brew 'sqlite'
brew 'python'
brew 'postgresql', restart_service: true
brew 'watchman'
brew 'yarn'
